---
language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - sshpass
  sonarcloud:
    organization: "gustavomcarmo-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - docker build --tag=esignbr/logistics .

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push esignbr/logistics
  - sshpass -p $FTP_PASSWORD sftp -o StrictHostKeyChecking=no -b sftp-commands $FTP_USER@esign.com.br
