---
language: java
jdk:
  - openjdk11

addons:
  apt:
    packages:
    - sshpass
  sonarcloud:
    organization: "gustavomcarmo-github"

install:
  - gem install travis

script:
  - mvn clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - mvn -s .travis.settings.xml source:jar deploy -DskipTests=true
  - sshpass -p $FTP_PASSWORD sftp -o StrictHostKeyChecking=no -o BatchMode=no -b sftp-commands $FTP_USER@esign.com.br
  - |
    if [ "$TRIGGER_TESTS" = "true" ]; then
      curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh;
      chmod +x trigger.sh;
      ./trigger.sh esign-consulting logistics-test-arquillian master $TRAVIS_GITHUB_TOKEN;
      ./trigger.sh esign-consulting logistics-test-jmeter master $TRAVIS_GITHUB_TOKEN;
      ./trigger.sh esign-consulting logistics-test-restassured master $TRAVIS_GITHUB_TOKEN;
      ./trigger.sh esign-consulting logistics-test-selenium master $TRAVIS_GITHUB_TOKEN;
    fi
