version: "3"
services:
  app:
    image: esignbr/logistics
    container_name: logistics
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - MONGODB_URI=mongodb://mongodb/logistics
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
