version: "3"
services:
  app:
    image: esignbr/logistics
    container_name: logistics
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
