version: "3"
services:
  app:
    image: esignbr/logistics
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: "mongodb"
