version: "2.4"
services:

  app:
    build: .
    image: esignbr/logistics
    container_name: logistics
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      - MONGODB_URI=mongodb://mongodb/logistics
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo
    container_name: mongodb
    healthcheck:
      test: ["CMD-SHELL", "mongo --quiet 127.0.0.1/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      interval: 10s
      timeout: 5s
      retries: 5
