---
- hosts: "{{ target | default('default') }}"

  roles:
    - codeyourinfra.docker_compose

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - language-pack-pt
        - python3-pip

    - name: Install required python packages
      pip:
        name: "{{ item }}"
      loop:
        - docker
        - docker-compose

    - name: Build the Logistics application (requires Maven)
      shell: mvn clean install
      delegate_to: localhost

    - name: Copy required files
      copy:
        src: "{{ item }}"
        dest: .
      loop:
        - logistics-ear
        - standalone.xml
        - Dockerfile
        - docker-compose.yml

    - name: Build the Logistics Docker image
      docker_image:
        name: esignbr/logistics
        path: .

    - name: Set up the Docker services
      docker_service:
        project_name: logistics
        project_src: .
