---
- hosts: "{{ target | default('default') }}"

  roles:
    - role: codeyourinfra.docker_compose

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - language-pack-pt
        - python3-pip

    - name: Install required python packages
      pip:
        name: "{{ item }}"
      loop:
        - docker
        - docker-compose

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: .

    - name: Set up the Docker services
      docker_service:
        project_name: logistics
        project_src: .
