---
- hosts: "{{ target | default('default') }}"

  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: .

    - name: Set up the Docker services
      docker_compose:
        project_name: logistics
        project_src: .

    - name: Wait until Logistics is up and running
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:8080/logistics"
      register: request
      until: request.status == 200
      retries: 20
      delay: 2
