name: Java CI/CD with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21.0.2
          cache: 'maven'
      - name: Build with Maven
        run: mvn verify sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} -ntp
      - name: Deploy to Maven Repository
        run: mvn -Dmaven.test.skip=true deploy -s settings.xml -ntp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
